import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { heightDP, widthDP } from "../../components/Responsive";
export const styles = StyleSheet.create({
  containers: {
    height: "90%",
    justifyContent: "flex-start",
    alignItems: "center",
    marginTop: 25,
  },
  conflictHeader: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginTop: 14,
    paddingVertical: 5,
  },
  keyboard: {
    flex: 1,
    justifyContent: "center",
  },
  image: {
    width,
    height,
  },
  header: {
    height: 65,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "white",
    paddingHorizontal: 20,
  },
  headeTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "black",
  },
  left: {
    flexDirection: "row",
    alignItems: "center",
  },
  right: {
    flexDirection: "row",
  },
  chatTitle: {
    color: "#fff",
    fontWeight: "600",
    margin: 10,
    fontSize: 15,
  },
  chatImage: {
    width: 30,
    height: 30,
    borderRadius: 15,
    margin: 5,
  },
  input: {
    flexDirection: "row",
    alignSelf: "flex-end",
    padding: 10,
    height: 40,
    width: width - 20,
    backgroundColor: "#fff",
    margin: 10,
    shadowColor: "#3d3d3d",
    shadowRadius: 2,
    shadowOpacity: 0.5,
    shadowOffset: {
      height: 1,
    },
    borderColor: "#696969",
    borderWidth: 1,
  },
  eachMsg: {
    flexDirection: "row",
    alignItems: "flex-end",
    margin: 5,
  },
  rightMsg: {
    flexDirection: "row",
    alignItems: "flex-end",
    margin: 5,
    alignSelf: "flex-end",
  },
  userPic: {
    height: 40,
    width: 40,
    margin: 5,
    borderRadius: 20,
    backgroundColor: "#f8f8f8",
  },
  msgBlock: {
    width: 220,
    borderRadius: 5,
    backgroundColor: "#ffffff",
    padding: 10,
  },
  rightBlock: {
    borderRadius: 5,
    backgroundColor: "#D9EDE6",
  },
  msgTxt: {
    fontSize: 15,
    color: "#555",
    fontWeight: "600",
  },
  rightTxt: {
    fontSize: 15,
    color: "#202020",
    fontWeight: "600",
  },
  timeTxt: {
    fontSize: 10,
    color: "black",
  },
  container: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: wp("5%"),
    position: "absolute",
    bottom: hp("0%"),
    width: wp("100%"),
    backgroundColor: "white",
    height: hp("10%"),
  },
  typemsgbody: {
    height: hp("5%"),
    width: wp("65%"),
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
    borderRadius: 100,
    paddingHorizontal: 10,
  },
  sendbtn: {
    height: hp("5%"),
    width: hp("5%"),
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#F0F5F8",
    paddingTop: Platform.OS == "ios" ? hp("2%") : 0,
  },
  modalView: {
    margin: 20,
    width: "80%",
    borderRadius: 20,
    justifyContent: "space-around",
    padding: 35,
    alignItems: "center",
    flexDirection: "row",
  },
  buttonClose: {
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
  },
  textStyle: {
    color: "black",
    fontSize: hp("1.8%"),
  },

  customTourContainer: { width: 220 },
  keyboard: {
    flex: 0.84,
    justifyContent: "center",
  },
  image: {
    width,
    height,
  },
  header: {
    height: 65,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#075e54",
  },
  left: {
    flexDirection: "row",
    alignItems: "center",
  },
  right: {
    flexDirection: "row",
  },
  chatTitle: {
    color: "#fff",
    fontWeight: "600",
    margin: 10,
    fontSize: 15,
  },
  chatImage: {
    width: 30,
    height: 30,
    borderRadius: 15,
    margin: 5,
  },
  input: {
    flexDirection: "row",
    alignSelf: "flex-end",
    padding: 10,
    height: 40,
    width: width - 20,
    backgroundColor: "#fff",
    margin: 10,
    shadowColor: "#3d3d3d",
    shadowRadius: 2,
    shadowOpacity: 0.5,
    shadowOffset: {
      height: 1,
    },
    borderColor: "#696969",
    borderWidth: 1,
  },
  eachMsg: {
    flexDirection: "row",
    alignItems: "flex-end",
    margin: 5,
  },
  rightMsg: {
    flexDirection: "row",
    alignItems: "flex-end",
    margin: 5,
    alignSelf: "flex-end",
  },
  userPic: {
    height: 40,
    width: 40,
    margin: 5,
    borderRadius: 20,
    backgroundColor: "#f8f8f8",
  },
  msgBlock: {
    borderRadius: 5,
    backgroundColor: "#ffffff",
  },
  rightBlock: {
    borderRadius: 5,
    backgroundColor: "#D9EDE6",
  },
  msgTxt: {
    width: 170,
    fontSize: 15,
    color: "#555",
    fontWeight: "600",
    padding: 10,
  },
  rightTxt: {
    fontSize: 15,
    color: "#202020",
    fontWeight: "600",
  },
  timeTxt: {
    fontSize: 10,
    color: "black",
  },
  Addfromgalleryicon: {
    height: hp("5%"),
    width: hp("5%"),
    borderRadius: 100,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    marginRight: 10,
    elevation: 5,
  },
  textinputbody: {
    height: "100%",
    width: "100%",
    fontFamily: "PR",
    fontSize: wp("13%"),
    color: "black",
  },
  pdf: {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
  },
  centeredView: {
    alignItems: "center",
  },
  button: {
    borderRadius: 20,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: "white",
  },
  header: {
    flex: 0.15,
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  chatThreadContainer: {
    // backgroundColor: "white",
    height: heightDP(90),
    borderRadius: 10,
    marginVertical: 5,
    flexDirection: "row",
    paddingHorizontal: 10,
  },
  threadHeaderContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 10,
  },
  pickerItems: {
    flexDirection: "row",
    padding: 20,
    borderBottomColor: "#e0dede",
    borderBottomWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  chatContainer: {
    backgroundColor: "white",
    height: 70,
    borderRadius: 10,
    marginVertical: 5,
    flexDirection: "row",
    paddingHorizontal: 10,
  },
  threadContainer: {
    flex: 1,
    paddingHorizontal: 20,
    backgroundColor: "#F0F5F8",
    paddingTop: hp("2%"),
  },
  picContainer: {
    flex: 0.2,
    justifyContent: "center",
    alignItems: "center",
  },
  pic: {
    height: hp("7%"),
    width: hp("7%"),
    borderRadius: 50,
  },
  textContainer: {
    flex: 0.7,
    justifyContent: "space-around",
    padding: 10,
  },
  profileName: {
    fontWeight: "bold",
    color: "black",
    fontSize: 16,
  },
  message: {
    color: "grey",
    fontSize: 11,
  },
  footer: {
    flex: 0.1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  messageCounter: {
    backgroundColor: "#57BE82",
    height: 17,
    width: 17,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  timeContainer: {
    height: "50%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  searchButtonContainer: {
    height: hp("7%"),
    width: hp("7%"),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
  },
});
